language: c
sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

after_success:
  - bash <(curl -s https://codecov.io/bash)
