language: r
sudo: required
dist: trusty
cache: packages

before_install:
- sudo apt-get install -y libgdal-dev libproj-dev

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
