---
title: "GSODRdata"
author: "Adam H. Sparks"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::knitr
  %\VignetteIndexEntry{GSODRdata
  %\VignetteEncoding{UTF-8
---

# GSODRdata: Climate and Ecological Data for the GSODR Package

 This data-only package was created for distributing data useful for the `GSODR`
 package and illustrated in examples given in the `GSODR` documentation. Four data
 frames are provided by this package. The first three fields are identical in
 all four dataframes and allow for linking with data generated by the 
 [`GSODR`](https://github.com/ropensci/GSODR) package, **STNID**, a unique code
 assigned to GSOD stations generated by the `GSODR` package.

For an example of the usage of these data, see the vignette, [Working with spatial and climate data](http://ropensci.github.io/GSODR/articles/Working_with_spatial_and_climate_data.html).

## CHELSA

[Climatic surfaces at 1 km resolution](http://chelsa-climate.org)

CHELSA data is based on a quasi-mechanistic statistical downscaling of the ERA interim global circulation model (Karger et al. 2016). ESA's CCI-LC cloud probability monthly averages are based on the MODIS snow products (MOD10A2).

### `CHELSA()`: A data frame with 23927 observations of 48 variables

  * STNID - Unique station ID  
  * CHELSA_bio1_1979-2013_V1_1 - Annual mean temperature [degree C]  
  * CHELSA_bio2_1979-2013_V1_1 - Mean diurnal range [degree C]  
  * CHELSA_bio3_1979-2013_V1_1 - Isothermality  
  * CHELSA_bio4_1979-2013_V1_1 - Temperature seasonality  
  * CHELSA_bio5_1979-2013_V1_1 - Maximum Temperature of warmest month [degree C]  
  * CHELSA_bio6_1979-2013_V1_1 - Minimum Temperature of coldest month [degree C]  
  * CHELSA_bio7_1979-2013_V1_1 - Temperature Annual Range [degree C]  
  * CHELSA_bio8_1979-2013_V1_1 - Mean Temperature of wettest quarter [degree C]  
  * CHELSA_bio9_1979-2013_V1_1 - Mean Temperature of driest quarter [degree C]  
  * CHELSA_bio10_1979-2013_V1_1 - Mean Temperature of warmest quarter [degree C]  
  * CHELSA_bio11_1979-2013_V1_1 - Mean Temperature of coldest quarter [degree C]  
  * CHELSA_bio12_1979-2013_V1_1 - Annual precipitation amount [mm]  
  * CHELSA_bio13_1979-2013_V1_1 - Precipitation of wettest month [mm]  
  * CHELSA_bio14_1979-2013_V1_1 - Precipitation of driest month [mm]  
  * CHELSA_bio15_1979-2013_V1_1 - Precipitation Seasonality  
  * CHELSA_bio16_1979-2013_V1_1 - Precipitation of wettest quarter [mm]  
  * CHELSA_bio17_1979-2013_V1_1 - Precipitation of driest quarter [mm]  
  * CHELSA_bio18_1979-2013_V1_1 - Precipitation of warmest quarter [mm]  
  * CHELSA_bio19_1979-2013_V1_1 - Precipitation of coldest quarter [mm]  
  * CHELSA_prec_1_1979-2013 - Mean January precipitation  
  * CHELSA_prec_2_1979-2013 - Mean February precipitation  
  * CHELSA_prec_3_1979-2013 - Mean March precipitation  
  * CHELSA_prec_4_1979-2013 - Mean April precipitation  
  * CHELSA_prec_5_1979-2013 - Mean May precipitation  
  * CHELSA_prec_6_1979-2013 - Mean June precipitation  
  * CHELSA_prec_7_1979-2013 - Mean July precipitation  
  * CHELSA_prec_8_1979-2013 - Mean August precipitation  
  * CHELSA_prec_9_1979-2013 - Mean September precipitation  
  * CHELSA_prec_10_1979-2013 - Mean October precipitation  
  * CHELSA_prec_11_1979-2013 - Mean November precipitation  
  * CHELSA_prec_12_1979-2013 - Mean December precipitation  
  * CHELSA_prec_1979-2013_land - Mean annual precipitation  
  * CHELSA_temp_1_1979-2013 - Mean January temperature  
  * CHELSA_temp_2_1979-2013 - Mean February temperature  
  * CHELSA_temp_3_1979-2013 - Mean March temperature  
  * CHELSA_temp_4_1979-2013 - Mean April temperature  
  * CHELSA_temp_5_1979-2013 - Mean May temperature  
  * CHELSA_temp_6_1979-2013 - Mean June temperature  
  * CHELSA_temp_7_1979-2013 - Mean July temperature  
  * CHELSA_temp_8_1979-2013 - Mean August temperature  
  * CHELSA_temp_9_1979-2013 - Mean September temperature  
  * CHELSA_temp_10_1979-2013 - Mean October temperature  
  * CHELSA_temp_11_1979-2013 - Mean November temperature  
  * CHELSA_temp_12_1979-2013 - Mean December temperature  
  * CHELSA_temp_1979-2013_land - Mean annual temperature  

### Note
 
 CHELSA (climatic surfaces at 1 km resolution) is based on a
 quasi-mechanistic statistical downscaling of the ERA interim global
 circulation model (Karger et al. 2016). ESA's CCI-LC cloud
 probability monthly averages are based on the MODIS snow products
 (MOD10A2).

### Source
 
CHELSA climate layers (http://chelsa-climate.org)

### Reference
 
Karger, D. N., Conrad, O., Bohner, J., Kawohl, T., Kreft, H., Soria-Auza,
R. W., *et al*. (2016) Climatologies at high resolution for the Earth land
surface areas. *arXiv preprint* **arXiv:1607.00217**.
 
------

## CRU_CL_2

[CRU CL 2.0 data-set](https://crudata.uea.ac.uk/~timm/grid/CRU_CL_2_0.html)

The CRU CL 2.0 data set (New *et al.* 2002) comprises monthly grids of observed mean climate from 1961-1990, and covering the global land surface at a 10 minute spatial resolution. There are eight climatic variables available, and also the elevations on the grid: diurnal temperature range, precipitation, mean temperature, wet-day frequency, frost-day frequency, relative humidity, sunshine, and wind-speed. In addition minimum and maximum temperature may be deduced from mean temperature and diurnal temperature range (see [FAQ](https://crudata.uea.ac.uk/~timm/grid/faq.html)).
 
### `CRU_CL_2()`: A data frame with 23927 observations of 99 variables

  * STNID - Unique station ID  
  * CRU_CL2_0_dtr_01 - Mean January diurnal temperature range [degrees Celsius]  
  * CRU_CL2_0_dtr_02 - Mean February diurnal temperature range [degrees Celsius]  
  * CRU_CL2_0_dtr_03 - Mean March diurnal temperature range [degrees Celsius]  
  * CRU_CL2_0_dtr_04 - Mean April diurnal temperature range [degrees Celsius]  
  * CRU_CL2_0_dtr_05 - Mean May diurnal temperature range [degrees Celsius]  
  * CRU_CL2_0_dtr_06 - Mean June diurnal temperature range [degrees Celsius]  
  * CRU_CL2_0_dtr_07 - Mean July diurnal temperature range [degrees Celsius]  
  * CRU_CL2_0_dtr_08 - Mean August diurnal temperature range [degrees Celsius]  
  * CRU_CL2_0_dtr_09 - Mean September diurnal temperature range [degrees Celsius]  
  * CRU_CL2_0_dtr_10 - Mean October diurnal temperature range [degrees Celsius]  
  * CRU_CL2_0_dtr_11 - Mean November diurnal temperature range [degrees Celsius]  
  * CRU_CL2_0_dtr_12 - Mean December diurnal temperature range [degrees Celsius]  
  * CRU_CL2_0_frs_01 - January ground-frost [number of days with ground-frost per month]  
  * CRU_CL2_0_frs_02 - February ground-frost [number of days with ground-frost per month]  
  * CRU_CL2_0_frs_03 - March ground-frost [number of days with ground-frost per month]  
  * CRU_CL2_0_frs_04 - April ground-frost [number of days with ground-frost per month]  
  * CRU_CL2_0_frs_05 - May ground-frost [number of days with ground-frost per month]  
  * CRU_CL2_0_frs_06 - June ground-frost [number of days with ground-frost per month]  
  * CRU_CL2_0_frs_07 - July ground-frost [number of days with ground-frost per month]  
  * CRU_CL2_0_frs_08 - August ground-frost [number of days with ground-frost per month]  
  * CRU_CL2_0_frs_09 - September ground-frost [number of days with ground-frost per month]  
  * CRU_CL2_0_frs_10 - October ground-frost [number of days with ground-frost per month]  
  * CRU_CL2_0_frs_11 - November ground-frost [number of days with ground-frost per month]  
  * CRU_CL2_0_frs_12 - December ground-frost [number of days with ground-frost per month]  
  * CRU_CL2_0_pre_01 - January precipitation [millimetres per month]  
  * CRU_CL2_0_pre_02 - February precipitation [millimetres per month]  
  * CRU_CL2_0_pre_03 - March precipitation [millimetres per month]  
  * CRU_CL2_0_pre_04 - April precipitation [millimetres per month]  
  * CRU_CL2_0_pre_05 - May precipitation [millimetres per month]  
  * CRU_CL2_0_pre_06 - June precipitation [millimetres per month]  
  * CRU_CL2_0_pre_07 - July precipitation [millimetres per month]  
  * CRU_CL2_0_pre_08 - August precipitation [millimetres per month]  
  * CRU_CL2_0_pre_09 - September precipitation [millimetres per month]  
  * CRU_CL2_0_pre_10 - October precipitation [millimetres per month]  
  * CRU_CL2_0_pre_11 - November precipitation [millimetres per month]  
  * CRU_CL2_0_pre_12 - December precipitation [millimetres per month]  
  * CRU_CL2_0_rd0_01 - January wet-days [no days with >0.1mm rain per month]  
  * CRU_CL2_0_rd0_02 - February wet-days [no days with >0.1mm rain per month]  
  * CRU_CL2_0_rd0_03 - March wet-days [no days with >0.1mm rain per month]  
  * CRU_CL2_0_rd0_04 - April wet-days [no days with >0.1mm rain per month]  
  * CRU_CL2_0_rd0_05 - May wet-days [no days with >0.1mm rain per month]  
  * CRU_CL2_0_rd0_06 - June wet-days [no days with >0.1mm rain per month]  
  * CRU_CL2_0_rd0_07 - July wet-days [no days with >0.1mm rain per month]  
  * CRU_CL2_0_rd0_08 - August wet-days [no days with >0.1mm rain per month]  
  * CRU_CL2_0_rd0_09 - September wet-days [no days with >0.1mm rain per month]  
  * CRU_CL2_0_rd0_10 - October wet-days [no days with >0.1mm rain per month]  
  * CRU_CL2_0_rd0_11 - November wet-days [no days with >0.1mm rain per month]  
  * CRU_CL2_0_rd0_12 - December wet-days [no days with >0.1mm rain per month]  
  * CRU_CL2_0_reh_01 - Mean January relative humidity [percent]  
  * CRU_CL2_0_reh_02 - Mean February relative humidity [percent]  
  * CRU_CL2_0_reh_03 - Mean March relative humidity [percent]  
  * CRU_CL2_0_reh_04 - Mean April relative humidity [percent]  
  * CRU_CL2_0_reh_05 - Mean May relative humidity [percent]  
  * CRU_CL2_0_reh_06 - Mean June relative humidity [percent]  
  * CRU_CL2_0_reh_07 - Mean July relative humidity [percent]  
  * CRU_CL2_0_reh_08 - Mean August relative humidity [percent]  
  * CRU_CL2_0_reh_09 - Mean September relative humidity [percent]  
  * CRU_CL2_0_reh_10 - Mean October relative humidity [percent]  
  * CRU_CL2_0_reh_11 - Mean November relative humidity [percent]  
  * CRU_CL2_0_reh_12 - Mean December relative humidity [percent]  
  * CRU_CL2_0_sun_01 - Mean January sunshine [percent of maximum possible (percent of day length)]  
  * CRU_CL2_0_sun_02 - Mean February sunshine [percent of maximum possible (percent of day length)]  
  * CRU_CL2_0_sun_03 - Mean March sunshine [percent of maximum possible (percent of day length)]  
  * CRU_CL2_0_sun_04 - Mean April sunshine [percent of maximum possible (percent of day length)]  
  * CRU_CL2_0_sun_05 - Mean May sunshine [percent of maximum possible (percent of day length)]  
  * CRU_CL2_0_sun_06 - Mean June sunshine [percent of maximum possible (percent of day length)]  
  * CRU_CL2_0_sun_07 - Mean July sunshine [percent of maximum possible (percent of day length)]  
  * CRU_CL2_0_sun_08 - Mean August sunshine [percent of maximum possible (percent of day length)]  
  * CRU_CL2_0_sun_09 - Mean September sunshine [percent of maximum possible (percent of day length)]  
  * CRU_CL2_0_sun_10 - Mean October sunshine [percent of maximum possible (percent of day length)]  
  * CRU_CL2_0_sun_11 - Mean November sunshine [percent of maximum possible (percent of day length)]  
  * CRU_CL2_0_sun_12 - Mean December sunshine [percent of maximum possible (percent of day length)]  
  * CRU_CL2_0_tmp_01 - Mean January temperature [degrees Celsius]  
  * CRU_CL2_0_tmp_02 - Mean February temperature [degrees Celsius]  
  * CRU_CL2_0_tmp_03 - Mean March temperature [degrees Celsius]  
  * CRU_CL2_0_tmp_04 - Mean April temperature [degrees Celsius]  
  * CRU_CL2_0_tmp_05 - Mean May temperature [degrees Celsius]  
  * CRU_CL2_0_tmp_06 - Mean June temperature [degrees Celsius]  
  * CRU_CL2_0_tmp_07 - Mean July temperature [degrees Celsius]  
  * CRU_CL2_0_tmp_08 - Mean August temperature [degrees Celsius]  
  * CRU_CL2_0_tmp_09 - Mean September temperature [degrees Celsius]  
  * CRU_CL2_0_tmp_10 - Mean October temperature [degrees Celsius]  
  * CRU_CL2_0_tmp_11 - Mean November temperature [degrees Celsius]  
  * CRU_CL2_0_tmp_12 - Mean December temperature [degrees Celsius]  
  * CRU_CL2_0_wnd_01 - Mean January 10 metre wind speed [metres per second]  
  * CRU_CL2_0_wnd_02 - Mean February 10 metre wind speed [metres per second]  
  * CRU_CL2_0_wnd_03 - Mean March 10 metre wind speed [metres per second]  
  * CRU_CL2_0_wnd_04 - Mean April 10 metre wind speed [metres per second]  
  * CRU_CL2_0_wnd_05 - Mean May 10 metre wind speed [metres per second]  
  * CRU_CL2_0_wnd_06 - Mean June 10 metre wind speed [metres per second]  
  * CRU_CL2_0_wnd_07 - Mean July 10 metre wind speed [metres per second]  
  * CRU_CL2_0_wnd_08 - Mean August 10 metre wind speed [metres per second]  
  * CRU_CL2_0_wnd_09 - Mean September 10 metre wind speed [metres per second]  
  * CRU_CL2_0_wnd_10 - Mean October 10 metre wind speed [metres per second]  
  * CRU_CL2_0_wnd_11 - Mean November 10 metre wind speed [metres per second]  
  * CRU_CL2_0_wnd_12 - Mean December 10 metre wind speed [metres per second]  

### Source
https://crudata.uea.ac.uk/cru/data/hrg/tmc/

### Reference
  
 New, M., Lister, D., Hulme, M., Makin, I. (2002) A high-resolution data
 set of surface climate over global land areas. *Climate Research* **21**:1-25
 ([abstract](https://crudata.uea.ac.uk/cru/data/hrg/tmc/readme.txt),
 [paper](http://www.int-res.com/articles/cr2002/21/c021p001.pdf))

------

## ESACCI

ESA's CCI-LC snow cover probability <http://maps.elie.ucl.ac.be/CCI/viewer/index.php>

### `ESACCI()`: A data frame with 23927 observations of 15 variables

  * STNID - Unique station ID  
  * ESACCI_snow_prob_Apr_500m - Mean April snow cover probability  
  * ESACCI_snow_prob_Aug_500m - Mean August snow cover probability  
  * ESACCI_snow_prob_Dec_500m - Mean December snow cover probability  
  * ESACCI_snow_prob_Feb_500m - Mean February snow cover probability  
  * ESACCI_snow_prob_Jan_500m - Mean January snow cover probability  
  * ESACCI_snow_prob_Jul_500m - Mean July snow cover probability  
  * ESACCI_snow_prob_Jun_500m - Mean June snow cover probability  
  * ESACCI_snow_prob_Mar_500m - Mean March snow cover probability  
  * ESACCI_snow_prob_May_500m - Mean May snow cover probability  
  * ESACCI_snow_prob_Nov_500m - Mean November snow cover probability  
  * ESACCI_snow_prob_Oct_500m - Mean October snow cover probability  
  * ESACCI_snow_prob_Sep_500m - Mean September snow cover probability  

### Source

ESA\'s CCI-LC snow cover probability (http://maps.elie.ucl.ac.be/CCI/viewer/index.php)


------
## MODCF

[Remotely sensed high-resolution global cloud dynamics for predicting ecosystem and biodiversity distributions](https://github.com/adammwilson/Cloud) 

MODCF (Wilson *et al.* 2016) provides new near-global, fine-grain (≈1km)
monthly cloud frequencies from 15 years of twice-daily MODIS satellite images.

### `MODCF()`: A data frame with 23927 observations of 17 variables

  * STNID - Unique station ID  
  * MODCF_meanannual - Mean annual cloud fraction  
  * MODCF_monthlymean_01 - Mean January cloud fraction  
  * MODCF_monthlymean_02 - Mean February fraction  
  * MODCF_monthlymean_03 - Mean March cloud fraction  
  * MODCF_monthlymean_04 - Mean April cloud fraction  
  * MODCF_monthlymean_05 - Mean May cloud fraction  
  * MODCF_monthlymean_06 - Mean June cloud fraction  
  * MODCF_monthlymean_07 - Mean July cloud fraction  
  * MODCF_monthlymean_08 - Mean August cloud fraction  
  * MODCF_monthlymean_09 - Mean September cloud fraction  
  * MODCF_monthlymean_10 - Mean October cloud fraction  
  * MODCF_monthlymean_11 - Mean November cloud fraction  
  * MODCF_monthlymean_12 - Mean December cloud fraction  
  * MODCF_seasonality_concentration - Cloud fraction seasonality concentration  

### Source

EarthEnv MODIS cloud fraction (http://www.earthenv.org/cloud)

### Reference

Wilson, A. M., Jetz, W. (2016) Remotely Sensed High-Resolution Global Cloud Dynamics
for Predicting Ecosystem and Biodiversity Distributions. *PLoS Biol* **14(3)**:
e1002415.

## WorlClim_Bio

WorlClim Global Climate Data - Free climate data for ecological
modeling and GIS http://www.worldclim.org/bioclim (Hijmans *et al.* 2004).

### `WorldClim_Bio()` A data frame with 26231 observations of 20 variables:

* STNID - Unique station ID to link to GSOD data from `GSODR`
* bio1 - Annual Mean Temperature
* bio2 - Mean Diurnal Range (Mean of monthly (max temp - min temp))
* bio3 - Isothermality (bio2 / bio7) (* 100)
* bio4 - Temperature Seasonality (standard deviation * 100)
* bio5 - Max Temperature of Warmest Month
* bio6 - Min Temperature of Coldest Month
* bio7 - Temperature Annual Range (bio5 - bio6)
* bio8 - Mean Temperature of Wettest Quarter
* bio9 - Mean Temperature of Driest Quarter
* bio10 - Mean Temperature of Warmest Quarter
* bio11 - Mean Temperature of Coldest Quarter
* bio12 - Annual Precipitation
* bio13 - Precipitation of Wettest Month
* bio14 - Precipitation of Driest Month
* bio15 - Precipitation Seasonality (Coefficient of Variation)
* bio16 - Precipitation of Wettest Quarter
* bio17 - Precipitation of Driest Quarter
* bio18 - Precipitation of Warmest Quarter
* bio19 - Precipitation of Coldest Quarter

### Source

WorldClim are freely available, average monthly climate data. Current
conditions (interpolations of observed data, representative of 1960-1990)
are freely available for download from http://www.worldclim.org/version1.
Climatic elements include minimum, mean and Mean Maximum temperature and
precipitation along with derived bioclimatic variables. WorldClim 1.4
(current conditions) are released under a Creative Commons
Attribution-ShareAlike 4.0 International License
http://creativecommons.org/licenses/by-sa/4.0/.


### Reference

Hijmans, R.J., S.E. Cameron, J.L. Parra, P.G. Jones and A.
Jarvis, 2005. Very high resolution interpolated climate surfaces for global
land areas. *International Journal of Climatology* **25**:1965-1978.

## WorlClim_Clim

WorlClim Global Climate Data - Free climate data for ecological
modeling and GIS http://www.worldclim.org/version1.

### `WorldClim_Clim()` A data frame with 26231 observations of 49 variables:

 * STNID - Unique station ID to link to GSOD data from `GSODR`
 * tmin1 - Mean Minimum Temperature for January
 * tmin2 - Mean Minimum Temperature for February
 * tmin3 - Mean Minimum Temperature for March
 * tmin4 - Mean Minimum Temperature for April
 * tmin5 - Mean Minimum Temperature for May
 * tmin6 - Mean Minimum Temperature for June
 * tmin7 - Mean Minimum Temperature for July
 * tmin8 - Mean Minimum Temperature for August
 * tmin9 - Mean Minimum Temperature for September
 * tmin10 - Mean Minimum Temperature for October
 * tmin11 - Mean Minimum Temperature for November
 * tmin12 - Mean Minimum Temperature for December
 * tmax1 - Mean Maximum Temperature for January
 * tmax2 - Mean Maximum Temperature for February
 * tmax3 - Mean Maximum Temperature for March
 * tmax4 - Mean Maximum Temperature for April
 * tmax5 - Mean Maximum Temperature for May
 * tmax6 - Mean Maximum Temperature for June
 * tmax7 - Mean Maximum Temperature for July
 * tmax8 - Mean Maximum Temperature for August
 * tmax9 - Mean Maximum Temperature for September
 * tmax10 - Mean Maximum Temperature for October
 * tmax11 - Mean Maximum Temperature for November
 * tmax12 - Mean Maximum Temperature for December
 * tmean1 - Mean Temperature for January
 * tmean2 - Mean Temperature for February
 * tmean3 - Mean Temperature for March
 * tmean4 - Mean Temperature for April
 * tmean5 - Mean Temperature for May
 * tmean6 - Mean Temperature for June
 * tmean7 - Mean Temperature for July
 * tmean8 - Mean Temperature for August
 * tmean9 - Mean Temperature for September
 * tmean10 - Mean Temperature for October
 * tmean11 - Mean Temperature for November
 * tmean12 - Mean Temperature for December
 * prec1 - Mean Precipitation for January
 * prec2 - Mean Precipitation for February
 * prec3 - Mean Precipitation for March
 * prec4 - Mean Precipitation for April
 * prec5 - Mean Precipitation for May
 * prec6 - Mean Precipitation for June
 * prec7 - Mean Precipitation for July
 * prec8 - Mean Precipitation for August
 * prec9 - Mean Precipitation for September
 * prec10 - Mean Precipitation for October
 * prec11 - Mean Precipitation for November
 * prec12 - Mean Precipitation for December

### Source 

WorldClim are freely available, average monthly climate data. Current
conditions (interpolations of observed data, representative of 1960-1990)
are freely available for download from http://www.worldclim.org/version1.
Climatic elements include minimum, mean, maximum temperature and
precipitation along with derived bioclimatic variables. WorldClim 1.4
(current conditions) are released under a Creative Commons
Attribution-ShareAlike 4.0 International License
http://creativecommons.org/licenses/by-sa/4.0/.

### Note 

Temperatures in `GSODRdata` are in degrees C, in the original
WorldClim data they are in degrees C * 10.

### Reference
Hijmans, R.J., S.E. Cameron, J.L. Parra, P.G. Jones and A.
Jarvis, 2005. Very high resolution interpolated climate surfaces for global
land areas. International Journal of Climatology 25: 1965-1978.
